version: '3'

networks:
  proxy:
    external: true

volumes:
  traefik-acme:
  shaarli-cache:
  shaarli-data:

services:
  shaarli:
    build: .
    volumes:
      - shaarli-cache:/var/www/shaarli/cache
      - shaarli-data:/var/www/shaarli/data
    ports:
      - '9090:80'
    networks:
      proxy:
